############## compose version ###############
##  compose file format       docker engine ##  
##  1	                      1.9.0+        ##
##  2.0	                      1.10.0+       ##
##  2.1	                      1.12.0+       ##
##  2.2, 3.0, 3.1, 3.2	      1.13.0+       ##
##  2.3, 3.3, 3.4, 3.5        17.06.0+      ##
##  2.4	                      17.12.0+      ##
##  3.6	                      18.02.0+      ##
##  3.7	                      18.06.0+      ##
##############################################
version: '3'
############# configure services #############
services:

################# database ################### 
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: bcs
      POSTGRES_DB: bcs-mattress
      POSTGRES_PASSWORD: bwtc@mattress
    ports:
      - "13432:5432"
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    restart: always

################## cacahe ####################
  cache:
    image: redis:alpine
    ports:
      - '11379:16379'
    environment:
      REDIS_PASSWORD: bwtc@mattress
    volumes:
      - ./cache/redis/redis.conf:/etc/redis/redis.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: /bin/sh -c "redis-server /etc/redis/redis.conf"
    restart: always

################### queue #####################
  queue:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
      - '8883:8883'
      - '9001:9001'
      - '8081:8081'
    volumes:
      - ./queue/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./queue/mqtt/mosquitto.pwd:/mosquitto/pwd.txt
      - $HOME/certs:/mosquitto/certs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

#################### file #####################
  file:
    image: atmoz/sftp:alpine
    ports:
      - '13222:22'
    volumes:
      - ./file/sftp/users.conf:/etc/sftp/users.conf:ro
      # - ./sftp/keys:/home/firmware/.ssh/keys:ro
      - ./file/sftp/stream:/home/yes/stream
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

#################### proxy ######################
  proxy:
    image: bewatec/jiaer-frontend:dev
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./proxy/mqtt.conf:/app/config.json:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

#################### agent ######################
  agent:
    image: bewatec/jiaer-agent:dev
    depends_on:
      - webapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    #ports:
      # - '2223:2222'
    volumes:
      - ./backend/agent/appsettings.json:/app/appsettings.json:ro
      - ./backend/agent/appsettings.json:/app/appsettings.Development.json:ro
      - ./backend/agent/logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

#################### webapi ######################
  webapi:
    image: bewatec/jiaer-webapi:dev
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8000
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - '8013:8000'
    volumes:
      - ./backend/webapi/appsettings.json:/app/appsettings.json:ro
      - ./backend/webapi/appsettings.json:/app/appsettings.Development.json:ro
      - ./backend/webapi/firms:/app/firms
      - ./backend/webapi/Keys:/app/Keys:ro
      - ./backend/webapi/logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
